services:
  worcable-app:
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.base
    container_name: worcable_nuxt
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - NODE_ENV=production
      - NUXT_DATABASE_URL=${DATABASE_URL:-mongodb://mongodb:27017/worcable}
      - NUXT_ENABLED_SERVICES=${ENABLED_SERVICES}
    
    networks:
      - worcable-network
    restart: always

  cvparser:
    profiles: ["cvparser"]
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile.cvparser
    container_name: worcable_cvparser
    ports:
      - "${CV_PARSER_PORT:-5000}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL:-mongodb://mongodb:27017/worcable}
      - ENABLED_SERVICES=${ENABLED_SERVICES}
    networks:
      - worcable-network
    restart: always

  mongodb:
    profiles: ["db"]
    image: mongo:latest
    container_name: worcable_db
    ports:
      - "${DATABASE_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - worcable-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

networks:
  worcable-network:
    driver: bridge

volumes:
  mongodb_data: