services:
  worcable-app:
    image: domutala/worcable-package:${IMAGE_TAG:-latest}
    container_name: worcable-${BRANCH_NAME:-main}
    restart: always
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - package.env
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_APP_VERSION=${IMAGE_TAG:-latest}
      
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"