services:
  base:
    image: domutala/worcable-package:${IMAGE_TAG:-latest}
    container_name: worcable-${BRANCH_NAME:-main}
    restart: always
    dns:
      - 8.8.8.8
      - 1.1.1.1
    ports:
      - "${HOST_PORT:-3000}:3000"
    env_file:
      - package.env
    environment:
      - NODE_ENV=production
      - NUXT_PUBLIC_APP_VERSION=${IMAGE_TAG:-latest}

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    labels:
      - "traefik.enable=true"
      # Configuration du routeur (Remplacez par votre domaine)
      - "traefik.http.routers.worcable-${BRANCH_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.worcable-${BRANCH_NAME}.entrypoints=web,websecure"
      - "traefik.http.routers.worcable-${BRANCH_NAME}.tls.certresolver=myresolver"
      # Indiquer le port interne de Nuxt à Traefik
      - "traefik.http.services.worcable-${BRANCH_NAME}.loadbalancer.server.port=3000"
      # - "traefik.http.services.whoami.loadbalancer.server.port=80"

      # Redirection automatique HTTP vers HTTPS
      - "traefik.http.routers.worcable-${BRANCH_NAME}-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.worcable-${BRANCH_NAME}-http.entrypoints=web"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.worcable-${BRANCH_NAME}-http.middlewares=redirect-to-https"

networks:
  traefik-public:
    external: true
