name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
      - dev
      - "release/*"

env:
  # On utilise Docker Hub
  REGISTRY: docker.io
  IMAGE_NAME: domutala/worcable-package

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            # If the push is on 'main', tag as 'latest'
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

            # If it's a release branch (release/v1.0), extract 'v1.0'
            type=ref,event=branch,suffix=,enable=${{ startsWith(github.ref, 'refs/heads/release/') }}

            # Always include the short SHA for traceability
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./package
          file: ./package/docker/Dockerfile
          build-args: |
            NUXT_PUBLIC_APP_VERSION=${{ github.ref_name }}

          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          # cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./package/docker/README.md
          short-description: Official Docker image for the main service of Worcable
