name: CI

on:
  push:
    branches:
      - main
      - develop
      - "release/*"

env:
  REGISTRY: docker.io
  IMAGE_NAME: domutala/worcable-package

jobs:
  push-docker-image:
    runs-on: ubuntu-latest
    name: Build and Publish Docker Image
    outputs:
      docker_tag: ${{ steps.set-tag.outputs.tag }}
      safe_branch: ${{ steps.set-tag.outputs.branch }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set outputs
        id: set-tag
        run: |
          # 1. Nettoyage du nom de branche (pour les noms de dossiers VPS)
          SAFE_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "branch=$SAFE_NAME" >> $GITHUB_OUTPUT

          # 2. Logique de Tag Docker
          if [ "${{ github.ref_name }}" == "main" ]; then
              # Règle 1: Main -> latest
              echo "tag=latest" >> $GITHUB_OUTPUT
              
          elif [[ "${{ github.ref_name }}" =~ ^release/ ]]; then
              # Règle 2: release/v1.0 -> v1.0
              # On récupère tout ce qui est après le dernier '/'
              VERSION=${{ github.ref_name }}
              echo "tag=${VERSION#*/}" >> $GITHUB_OUTPUT
              
          else
              # Règle 3: Autre -> sha-short (fourni par metadata-action)
              # On récupère le format court via github.ref_name

              BRANCH_NAME=${{ github.ref_name }}
              echo "tag=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: type=raw,value=${{steps.set-tag.outputs.tag}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./package
          file: ./package/docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NUXT_PUBLIC_APP_VERSION=${{ steps.set-tag.outputs.tag }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ env.IMAGE_NAME }}
          readme-filepath: ./package/docker/README.md
