name: Release CLI

on:
  push:
    branches:
      - develop
    # tags:
    #   - "cli/*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create and Push Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag v1.0.${{ github.run_number }}
          git push origin v1.0.${{ github.run_number }}

      # - name: Create a GitHub release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: cli-${{ steps.tag_version.outputs.new_tag }}
      #     name: Release ${{ steps.tag_version.outputs.new_tag }}
      #     body: ${{ steps.tag_version.outputs.changelog }}


      # - name: Enable Corepack
      #   run: npm i -g --force corepack && corepack enable

      # - name: Install dependencies
      #   run: |
      #     cd cli
      #     pnpm install --frozen-lockfile
      #     pnpm build

      # - uses: oven-sh/setup-bun@v1

      # - name: Build CLI
      #   run: |
      #     cd cli
      #     bun build src/index.ts --compile --outfile worcable

      # - name: Rename binary
      #   run: mv cli/worcable worcable-linux

      # - name: Upload release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: worcable-linux
      #     tag_name: ${{ github.ref_name }}

# git push origin cli/1.0.0