name: Release CLI

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create cli tag
        run: |
          git tag cli/${{ github.ref_name }}
          git push origin cli-v1.0.0

