name: Release CLI

on:
  push:
    branches:
      - main
      - develop
      - "release/*"
   
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tag_name: ${{ steps.set-tag-name.outputs.name }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Set tag name
        id: set-tag-name
        run: |
          # 1. Nettoyage du nom de branche (pour les noms de dossiers VPS)
          SAFE_NAME=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "branch=$SAFE_NAME" >> $GITHUB_OUTPUT

          # 2. Logique de Tag Docker
          if [ "${{ github.ref_name }}" == "main" ]; then
              # Règle 1: Main -> latest
              echo "name=latest" >> $GITHUB_OUTPUT
              
          elif [[ "${{ github.ref_name }}" =~ ^release/ ]]; then
              # Règle 2: release/v1.0 -> v1.0
              # On récupère tout ce qui est après le dernier '/'
              VERSION=${{ github.ref_name }}
              echo "name=${VERSION#*/}" >> $GITHUB_OUTPUT
              
          else
              # Règle 3: Autre -> sha-short (fourni par metadata-action)
              # On récupère le format court via github.ref_name

              BRANCH_NAME=${{ github.ref_name }}
              echo "name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          fi
          
      - name: Create tag
        run: |
          TAG="${{ steps.set-tag-name.outputs.name }}"

          echo "Checking if tag $TAG exists..."

          if git ls-remote --tags origin | grep -q "refs/tags/$TAG"; then
            echo "Tag already exists on remote"
          else
            git tag $TAG
            git push origin $TAG
          fi

          git push origin $TAG

      - name: Enable Corepack
        run: npm i -g --force corepack && corepack enable

      - name: Install dependencies
        run: |
          cd cli
          pnpm install --frozen-lockfile
          pnpm build

      - uses: oven-sh/setup-bun@v1

      - name: Build CLI
        run: |
          cd cli
          bun build src/index.ts --compile --outfile worcable

      - name: Rename binary
        run: mv cli/worcable worcable-linux

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: worcable-linux
          tag_name: ${{ steps.set-tag-name.outputs.name }}
